
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "token_api": "e0cfc124",
    "password": "test"
}

###

GET http://localhost:3003/api/users

###

PUT http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "test",
    "favoriteMovies": []
}

###

GET http://localhost:3003/api/movies